Migrate the infra-did-parachain
InfraBlockchain/infrablockspace-sdk pull request #23
Opened 2023-11-23 11:07 UTC by energyGiver

# Summary
- migrate the infra-did-parachain from the latest dock-substrate into the `infrablockspace-sdk`
- add the `did-core` pallet and `did-infra` runtime

# Changes
- fix serveral conflicts due to version-up
- fix the serde feature error
- delete unused comments for docs

# ToDo
- add a trusted_entity module
- delete deprecated features due to a version conflict

2023-11-23 23:28 UTC, sweatpotato13 commented
`cargo +nightly fmt` 포맷팅 해주세요

2023-11-23 23:35 UTC, sweatpotato13 requested changes
🐧

2023-11-23 23:35 UTC, sweatpotato13 commented on cumulus/infra-parachain/src/chain_spec/did.rs
> +			"/ip4/34.65.251.121/tcp/30334/p2p/12D3KooWG3GrM6XKMM4gp3cvemdwUvu96ziYoJmqmetLZBXE8bSa".parse().unwrap(),
bootnode 관련 옵션은 비워두고 저희 네트워크가 릴리즈 됐을 때 저희가 구축한 bootnode로 연결하는게 맞는 것 같습니다

2023-11-23 23:35 UTC, sweatpotato13 commented on cumulus/infra-parachain/src/chain_spec/did.rs
> +			"/ip4/34.65.251.121/tcp/30334/p2p/12D3KooWG3GrM6XKMM4gp3cvemdwUvu96ziYoJmqmetLZBXE8bSa".parse().unwrap(),
DID말고 다른 chain_spec에 있는것도 같이 지워주세요

2023-11-23 23:35 UTC, sweatpotato13 commented on cumulus/zombienet/ibs-local-network.toml
> +# [[parachains]]
AssetHub, URAuth 주석 풀어주세요

2023-11-24 01:15 UTC, cocoyoon commented on Cargo.toml
> +default-members = ["infrablockspace", "cumulus/parachain-template/node", "cumulus/infra-parachain"]
Parity 의 `default-members` 목적은 polkadot-sdk 를 빌드할 때 `polkadot` 바이너리만 빌드되게끔 하는 거였습니다.  - 저희도 따라가는 방안
-`default-members` 삭제하는 방안
을 결정해야할거 같습니다.

2023-11-24 01:20 UTC, cocoyoon commented on substrate/frame/did-core/src/common/keys.rs
> +	Deserialize,
이거 두개도 #[feature="serde"] 로 묶여야 하지 않아요?

2023-11-24 01:22 UTC, cocoyoon commented on substrate/frame/did-core/src/modules/did/service_endpoints.rs
> +#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
매크로 너무 복잡해서 좀 파악되면 줄일 수 있는건 줄이는 방향으로 가시죠

2023-11-24 01:29 UTC, cocoyoon approved these changes

2023-11-24 02:18 UTC, energyGiver commented on cumulus/zombienet/ibs-local-network.toml
> +# [[parachains]]
applied it!

2023-11-24 02:18 UTC, energyGiver commented on cumulus/infra-parachain/src/chain_spec/did.rs
> +			"/ip4/34.65.251.121/tcp/30334/p2p/12D3KooWG3GrM6XKMM4gp3cvemdwUvu96ziYoJmqmetLZBXE8bSa".parse().unwrap(),
applied it!

2023-11-24 02:18 UTC, energyGiver commented on substrate/frame/did-core/src/common/keys.rs
> +	Deserialize,
applied it!

2023-11-24 02:18 UTC, energyGiver commented on substrate/frame/did-core/src/modules/did/service_endpoints.rs
> +#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
got it!

2023-11-24 02:36 UTC, sweatpotato13 approved these changes
👍

2023-11-24 02:40 UTC, merged