Feature/44 enhance newnal pallet for datamarket
InfraBlockchain/infrablockspace-sdk pull request #45
Opened 2024-01-03 02:29 UTC by energyGiver

✄ -----------------------------------------------------------------------------

Thank you for your Pull Request! 🙏 Please make sure it follows the contribution guidelines outlined in
[this document](https://github.com/paritytech/polkadot-sdk/blob/master/docs/CONTRIBUTING.md) and fill
out the sections below. Once you're ready to submit your PR for review, please
delete this section and leave only the text under the "Description" heading.

# Description

*Please include a summary of the changes and the related issue. Please also include relevant motivation and context,
including:*

- What does this PR do?
- Why are these changes needed?
- How were these changes implemented and what do they affect?

*Use [Github semantic
linking](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
to address any open issues this PR relates to or closes.*

Fixes # (issue number, *if applicable*)

Closes # (issue number, *if applicable*)

# Checklist

- [ ] My PR includes a detailed description as outlined in the "Description" section above
- [ ] My PR follows the [labeling requirements](CONTRIBUTING.md#Process) of this project (at minimum one label for `T`
  required)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

You can remove the "Checklist" section once all have been checked. Thank you for your contribution!

✄ -----------------------------------------------------------------------------

2024-01-09 05:22 UTC, sweatpotato13 requested changes
🐧

2024-01-09 05:22 UTC, sweatpotato13 commented on cumulus/infra-parachain/src/chain_spec/newnal.rs
>  pub type URAuthChainSpec =
이것도 변수명 변경 해주세요

2024-01-09 05:22 UTC, sweatpotato13 commented on cumulus/infra-parachain/src/chain_spec/newnal.rs
>  		ChainType::Local,
Dev 컨픽은 `ChainType::Development` 으로 변경해주세요

2024-01-09 05:22 UTC, sweatpotato13 commented on cumulus/infra-parachain/src/chain_spec/newnal.rs
>  		"InfraBlockchain URAuth Dev",
"InfraBlockchain URAuth Dev" -> "InfraBlockchain Newnal Dev"

2024-01-09 05:22 UTC, sweatpotato13 commented on substrate/frame/data-market/src/lib.rs
> +	pub(super) type CurrentPurchaseId<T: Config> = StorageValue<_, PurchaseId, ValueQuery>;
다음 호출 될`register_data_purchase` 과정에서 현재 스토리지에 담긴 값을 다음 ID로 사용하는데 
로직 상 `CurrentPurchaseId` 보단 `NextPurchaseId` 가 적합해 보입니다.

2024-01-09 05:22 UTC, sweatpotato13 commented on substrate/frame/newnal/Cargo.toml
> +name = "pallet-newnal"
이 팔렛은 URAuth의 관리에 대한 pallet이 맞아서 이름을 유지하는 것이 맞는거같은데 어떻게 생각하시나요

2024-01-09 05:36 UTC, energyGiver commented on substrate/frame/data-market/src/lib.rs
> +	pub(super) type CurrentPurchaseId<T: Config> = StorageValue<_, PurchaseId, ValueQuery>;
현재 register_data_purchase call에서 get한 값을 등록할 때 사용하는데 CurrentPurchaseId가 맞지 않을까요?

2024-01-09 05:37 UTC, energyGiver commented on substrate/frame/newnal/Cargo.toml
> +name = "pallet-newnal"
pallet-urauth 하나로 통합하자는 말씀이신가요?

2024-01-09 05:45 UTC, energyGiver commented on substrate/frame/newnal/Cargo.toml
> +name = "pallet-newnal"
동의합니다!

2024-01-09 05:45 UTC, sweatpotato13 commented on substrate/frame/newnal/Cargo.toml
> +name = "pallet-newnal"
pallet-urauth는 기존 phase1 pallet 아닌가요?
마켓은 별도로 pallet-data-market 라는 이름으로 있는거같아서요

2024-01-09 05:47 UTC, sweatpotato13 commented on substrate/frame/data-market/src/lib.rs
> +	pub(super) type CurrentPurchaseId<T: Config> = StorageValue<_, PurchaseId, ValueQuery>;
register_data_purchase가 호출되어 로직이 진행중인 상황에서는 Current가 맞는데 
호출되지않을땐 Next 값이라서 Next가 좀 더 어울리지 않을까 했습니다.

실제 스토리지를 조회하는 순간에는 register_data_purchase가 호출되는 순간은 아닐테니까요

2024-01-09 05:57 UTC, energyGiver commented on substrate/frame/data-market/src/lib.rs
> +	pub(super) type CurrentPurchaseId<T: Config> = StorageValue<_, PurchaseId, ValueQuery>;
반영했습니다!

2024-01-09 06:07 UTC, sweatpotato13 approved these changes
👍

2024-01-09 07:16 UTC, cocoyoon commented on substrate/frame/urauth/src/lib.rs
> +			Self::try_store_updated_newnal_doc(
Runtime 명만 `Newnal` 바뀌는거 아닌가요? frame 안에있는 `urauth` 까지 바뀔 필요는 없을거같아요

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/urauth/src/lib.rs
> +
해당 타입들은 data-market 에 정의되어야 하지 않아요?

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/urauth/src/lib.rs
> +			newnal_doc: URAuthDoc<T::AccountId>,
Runtime 명만 `Newnal` 바뀌는거 아닌가요? frame 안에있는 `urauth` 까지 바꾸는거에요?

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +const MIN_PLATFORM_FEE_RATIO: u32 = 1_000;
`types` 모듈로 빼는게 좋아보입니다

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +
`types` 모듈이 좋아보입니다

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +
`AnyText` 까지`pallet::config` 에 정의하고 
`DataPurchaseRegisterDetails<T: Config>` 로 정의하면 깔끔할거 같아요

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +		StorageMap<_, Twox64Concat, PurchaseId, u32, ValueQuery>;
`u32` 도 alias 로 감싸는게 어떠신가요 `type TradeCount = u32`

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +		) -> DispatchResult {
`data_*` 변수명에서 `data` 는 빼는게 어떤지 의견드립니다

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +			system_token_id: u32,
`asset_id` 가 맞아 보입니다. 아니면 `system_token_asset_id`

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +					origin.clone(),
내부 메소드로 변경하는게 좋을거같아요

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +					TOTAL_FEE_RATIO - MIN_PLATFORM_FEE_RATIO,
Pallet 내부 function 으로 작성해주시면 좋을거같아요
`ensure!(Self::check_*(), Error)`

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +		#[pallet::weight(10_000)]
`dev_mode` 로 변경해주시고 `pallet::weight` 는 지워주세요(나머지 포함)

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +
- `types` 로 이동
- `deadline` 을 고려해서 `Stale` 도 추가하면 좋을거같아요. `Stale` 상태에 있는 Purchase들은 Session 이나 특정 기간에 한번에 없애주는 식으로 진행하고요. 
- `Finished` 보다 `Completed` 나 `InActive` 로 두는게 좋을거같아요

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +			ensure!(data_verifiers.contains(&origin_verifier), Error::<T>::InvalidVerifier);
`Self::check_execution_validity()` 로 묶어주는게 어때요?

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +			let origin_verifier = ensure_signed(origin)?;
`maybe_verifier` 로 변경하는게 좋아보여요

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +				return Err(Error::<T>::AccountAlreadyExists.into())
`AccountAlreadyExists` 에러는 의미가 모호하니 `AlreadyTraded` 가 좋아보입니다

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +		)?;
이것도 내부 메소드로 변경해주세요

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +		)?;
내부 메소드로!

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +		}
내부 메소드!

2024-01-09 07:54 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +		pub fn execute_data_trade(
`purchase_deadline` 을 고려해야 하는 로직이 필요할거 같아요. `Active` 상태이지만 `deadline` 이 지난 시점이면 `Stale` 로 변경하는 식으로요

2024-01-09 08:29 UTC, energyGiver commented on substrate/frame/urauth/src/lib.rs
> +			newnal_doc: URAuthDoc<T::AccountId>,
urauth가 맞습니다- 다시 원복했습니다!

2024-01-10 00:28 UTC, energyGiver commented on substrate/frame/data-market/src/lib.rs
> +		) -> DispatchResult {
bez가 앞에 data가 없으면 모호할 수 있다고 해서 추가했습니다!

2024-01-10 02:02 UTC, energyGiver commented on substrate/frame/data-market/src/lib.rs
> +					TOTAL_FEE_RATIO - MIN_PLATFORM_FEE_RATIO,
따로 function 추가하는 것보다 ensure 그대로 두고, 가독성 고려해서 다음과 같이 수정하였습니다
```
let sum_fee_ratio = data_issuer_fee_ratio + data_owner_fee_ratio + MIN_PLATFORM_FEE_RATIO;
ensure!(
sum_fee_ratio <= TOTAL_FEE_RATIO,
Error::<T>::InvalidFeeRatio
);
```

2024-01-10 02:05 UTC, energyGiver commented on substrate/frame/data-market/src/lib.rs
> +			ensure!(data_verifiers.contains(&origin_verifier), Error::<T>::InvalidVerifier);
따로 function 만들면 입력 parameter가 많고 각 ensure logic 기능도 달라서 그대로 두는 것도 가독성 괜찮을 것 같습니다!

2024-01-29 02:25 UTC, cocoyoon commented on substrate/frame/urauth/src/types.rs
> +		let raw_uri = "newnal://file/cid".as_bytes().to_vec();
여기는 `newnal` 인가요?

2024-01-29 02:25 UTC, cocoyoon commented on substrate/frame/data-market/src/types.rs
> +}
- `data_verifiers` : `AccountId` 로 단일 타입으로 변경
- `u32` 타입들 `codec(compact)` 적용
- `purchase_deadline` 의 deadline 을 확인할 수 있는 내부 메소드 구현하면 좋을거 같아요 
```rust
impl DataPurchaseDetail {
    fn is_expired(n: BlockNumber) {}
}
```
- `DataPurchaseInfo` 같은건 `DataPurchaseMetadata` 를 따로 두는게 좋아보여요. 해당 `Detail` 같은 경우 Runtime 동안 많은 조회가 이루어질 것이기 때문에 Runtime 상에서 필요한 필드만 있으면 될거 같습니다

2024-01-29 02:25 UTC, cocoyoon commented on substrate/frame/data-market/src/types.rs
> +	Stale,
각 variant 간 어떤 status 인지에 대한 주석 달아주세요

2024-01-29 02:25 UTC, cocoyoon commented on substrate/frame/data-market/src/types.rs
> +pub const MIN_PLATFORM_FEE_RATIO: u32 = 1_000;
`[pallet::constant]` 로 빼는게 좋아보여요

2024-01-29 02:25 UTC, cocoyoon commented on substrate/frame/data-market/src/lib.rs
> +	pub trait Config: frame_system::Config + pallet_assets::Config {
`pallet_assets::Config` 에 tightly-coupled 는 불필요해 보입니다. loosely-coupled 로 `Balanced` trait 이용해서 변경하는게 좋아보여요. 그러면 internal 메소드도 불필요해지고 `(super)` 도 다시 돌릴 수 있습니다. 

```
..
type assets: Balanced<Self::AcccountId>;
```

2024-01-30 23:57 UTC, sweatpotato13 commented on substrate/frame/urauth/src/types.rs
> +		let raw_uri = "newnal://file/cid".as_bytes().to_vec();
저 부분은 프로토콜인 urauth가 더 자연스러운 것 같습니다.

2024-02-02 11:07 UTC, energyGiver commented on substrate/frame/data-market/src/lib.rs
> +	pub trait Config: frame_system::Config + pallet_assets::Config {
좋습니다 다음 issue에 반영하겠습니다!

2024-02-05 04:56 UTC, cocoyoon approved these changes

2024-02-05 05:23 UTC, merged